### ISSUE TITLE
Accent Positioning Roman lowercase /dotbelow

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/josefinsans#14]
/dotbelow is migrating across weight

also, in the lightweight Italic 
this /aacute issue appears in the currently served fonts
but please align it because it differs from other lc accent positioning

![:dotbelow](https://user-images.githubusercontent.com/6576107/68826995-72c67780-066e-11ea-9502-71718556a870.png)

![:aacute](https://user-images.githubusercontent.com/6576107/68827001-7528d180-066e-11ea-846a-537fce1c2110.png)

**Comment by djrrb** [comment]
@pichotta I believe the dotbelow thing is similar to the tilde issue, because the dot below is a component.

I still think this is a bug in fontmake or diffenator, as the source data with a component of a component should be okay. But if you’d prefer for me to just decompose, let me know.

**Comment by pichotta** [comment]
@djrrb yes, please resolve in same way as tilde

**Comment by djrrb** [comment]
The accent heights are all over the place in this font, and aligning everything seemed like it would be going too far. But I did offset the `acute` across styles.

As far as the dot below, I think we can let fontmake solve this. If we need an immediate solve, we can add these glyphs to the lib, but I think it’s cleaner to let them update the tool to do this automatically than to store the extra data. https://github.com/googlefonts/fontmake/issues/595#issuecomment-554424520
