### ISSUE TITLE
JosefinSans-Italic.ttf and JosefinSans-SemiBoldItalic.ttf are not generating

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/josefinsans#18]
It seems these two fonts are not included in the ttf or otf dirs. 

The VFs do contain these instances though.

<img width="865" alt="Screenshot 2019-12-02 at 16 29 47" src="https://user-images.githubusercontent.com/7525512/69976495-fa423080-1520-11ea-954e-e0dd05ac9082.png">

I regenned the fonts and they didn't appear so they weren't accidentally deleted.

A good find by @thlinard, https://github.com/google/fonts/pull/2267#issuecomment-560454338

**Comment by djrrb** [comment]
fixed in #19
