### ISSUE TITLE
/ff

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/josefinsans#6]
The /ff needs to be resolved in the masters.  
Oddly, the Bold Italic html proof showed it is missing... but the fonts shows them missing in the romans?

![Josefin Sans :ff](https://user-images.githubusercontent.com/6576107/67521652-4c1dae00-f679-11e9-956f-e56a136db3f8.png)

**Comment by djrrb** [comment]
Okay, I have made the glyph name `f_f` consistent in all masters, set unicodes in all masters, and regenerated.

I did not fix the inconsistency between the spaced-out bold italic and the colliding bold, as I did not want to change spacing.
